#ifndef APP_H_
#define APP_H_


typedef enum 
{
    MAIN_MENU,
    MAIN_MENU_WAIT_FOR_INPUT,
    CLEANUP_MODE_MENU,
    CLEANUP_MODE_WAIT_FOR_INPUT,
    CLEANUP_MODE_WAIT_FOR_COMPLETE,
    CALIBRATION_MODE_MENU,
    SELECT_WEIGHT,
    SELECT_WEIGHT_WAIT_FOR_INPUT,
    POWDER_THROW,
    POWDER_THROW_WAIT_FOR_INPUT,
    POWDER_THROW_WAIT_FOR_COMPLETE,
    POWDER_TRICKLE,
    POWDER_TRICKLE_WAIT_FOR_INPUT,
    POWDER_TRICKLE_WAIT_FOR_STABLE,
    POWDER_TRICKLE_WAIT_FOR_CONFIRM,
} TricklerState_t;



#endif  // APP_H_